// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbl8e2Eklqn-q_xOKpZ2VWUrlJ8yX9fLo',
    appId: '1:726406145652:web:a991f29cbd8ed94e471321',
    messagingSenderId: '726406145652',
    projectId: 'swiftly-d9fc4',
    authDomain: 'swiftly-d9fc4.firebaseapp.com',
    storageBucket: 'swiftly-d9fc4.firebasestorage.app',
    measurementId: 'G-BV2CK6S025',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvO9EyG3VsNz_84L-isKmTlQRm9ldhnak',
    appId: '1:726406145652:android:0fa7f43de473fcfc471321',
    messagingSenderId: '726406145652',
    projectId: 'swiftly-d9fc4',
    storageBucket: 'swiftly-d9fc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgAnvZnVGPmmJCBCl_uhQwXNb6I9dl3R0',
    appId: '1:726406145652:ios:859cf2427b266ed5471321',
    messagingSenderId: '726406145652',
    projectId: 'swiftly-d9fc4',
    storageBucket: 'swiftly-d9fc4.firebasestorage.app',
    iosBundleId: 'com.example.swiftly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgAnvZnVGPmmJCBCl_uhQwXNb6I9dl3R0',
    appId: '1:726406145652:ios:859cf2427b266ed5471321',
    messagingSenderId: '726406145652',
    projectId: 'swiftly-d9fc4',
    storageBucket: 'swiftly-d9fc4.firebasestorage.app',
    iosBundleId: 'com.example.swiftly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbl8e2Eklqn-q_xOKpZ2VWUrlJ8yX9fLo',
    appId: '1:726406145652:web:7cf468df92aadaa5471321',
    messagingSenderId: '726406145652',
    projectId: 'swiftly-d9fc4',
    authDomain: 'swiftly-d9fc4.firebaseapp.com',
    storageBucket: 'swiftly-d9fc4.firebasestorage.app',
    measurementId: 'G-XE7G2GLSD8',
  );
}
